[package]
name = "esc-client-generated"
version = "0.1.0"
authors = ["Tim Simpson <timsimpson4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esc-client-base = { path = "../base"}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "2.1"
http = "0.2"
log = "0.4"
validator = "0.10"
chrono = { version = "0.4", features = ["serde"] }
bytes = "0.5"
reqwest = { version = "0.11", features = ["json", "rustls-tls-native-roots"] }
urlencoding = "1.3.3"

[dev-dependencies]
regex = "1.5.4"
tokio = { version = "1.18", features = ["macros", "fs"] }
