'!include': '../target/input.yaml'
'!include': '../target/rust-esc-output.yaml'
'!include': 'rust-common.yaml'
generatorName: rust
templateDir: templates/rust-esc/mustache
packageName: escApi
additionalProperties: 
  useSingleRequestParameter: true 