openapi: "3.0.0"
info:
  title: EventStore Cloud
  version: 0.1.0
  description: APIs for EventStore API
  termsOfService: http://swagger.io/terms/
  contact:
    name: EventStore API
    email: esc@eventstore.com
    url: https://eventstore.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.eventstore.cloud/resources/v1
paths:
  /organizations:
    $ref: 'resources/organizations.yaml#/paths/organizations'    
  /organizations/{organizationId}:
    $ref: 'resources/organizations.yaml#/paths/organizations-{organizationId}'
  /organizations/{organizationId}/projects:
    $ref: 'resources/projects.yaml#/paths/organizations-{organizationId}-projects'
  /organizations/{organizationId}/projects/{projectId}:
    $ref: 'resources/projects.yaml#/paths/organizations-{organizationId}-projects-{projectId}'
components:  
  securitySchemes:
    esc_auth:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://api.example.com/docs/auth)
      flows:
        implicit:
          authorizationUrl: https://identity.eventstore.com
          scopes: {}
    token:
      type: apiKey
      name: Authorization
      in: header