name: CI

on:
  - pull_request

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        rust: [stable, beta, nightly]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: rustup default ${{ matrix.rust }}
      - name: Build
        run: cargo check
        continue-on-error: ${{ matrix.rust == 'nightly' }}

  linting:
    name: Linting
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
          rustup component add clippy-preview
          rustup component add rustfmt
      - name: Linting
        run: cargo clippy -- -D warnings
      - name: Formatting
        run: cargo fmt -- --check