name: CI

on:
  - pull_request

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v1      
      - name: install Just
        run: cargo install just --version 1.2.0
      - name: Build and Test
        run: just ci
