name: CI

on:
  - pull_request

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Install current stable Rust compiler
        run: |
          rustup update
          rustup default stable
      - name: install Just
        uses: extractions/setup-just@v1
        with:
          just-version: 1.14.0
      - name: Build and Test
        run: just ci
