name: Nightly

on:
  schedule:
    - cron: '0 3 * * *' # Every day at 3am UTC.

jobs:
  release:
    name: Release
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Lookup or create release
        uses: EventStore/Automations/lookup-or-create-release@master
        id: release
        with:
          build-type: nightly
          github-token: ${{ secrets.GH_PAT }}